version: '3'

services:
  MatrixBackend:
    image: 'docker-spring-boot-matrix:latest'
    platform: linux/arm64/v8
    #    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: .
    container_name: MatrixBackend
    depends_on:
      - db
    environment: # Pass environment variables to the service
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mar335832
      - DATABASE_NAME=matrixdb
      - DATABASE_PORT=3306
  db:
    image: mysql
    platform: linux/x86_64
    #    platform: linux/amd64
    environment:
      MYSQL_DATABASE: matrixdb
      MYSQL_ROOT_PASSWORD: mar335732
    ports:
      - "3307:3306"
#  nginx:
#    container_name: service_nginx
#    image: nginx:latest
#    volumes:
#      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    ports:
#      - "80:80"
#      - "443:443"

